export const semanticMetrics = [
  { id: "uploaded", label: "Uploaded videos", available: true },
  { id: "processed", label: "Processed videos", available: true },
  { id: "published", label: "Published videos", available: true },
  { id: "reels", label: "Reels", available: true },
  { id: "chapters", label: "Chapters", available: true },
  { id: "shortsVideos", label: "Shorts videos", available: true },
  { id: "mkmVideos", label: "MKM videos", available: true },
  { id: "viralVideos", label: "Viral videos", available: true },
  { id: "replacedVideos", label: "Replaced videos", available: true },
  { id: "nonBillableVideos", label: "Non-billable videos", available: true },
  { id: "videosDownloaded", label: "Videos downloaded", available: false },
  { id: "videosIngested", label: "Original videos ingested", available: true },
  { id: "generatedOutputs", label: "Generated outputs", available: true },
  { id: "processingSuccessRate", label: "Processing success rate", available: true },
  { id: "processingErrorRate", label: "Processing error rate", available: true },
  { id: "processingBacklog", label: "Processing backlog", available: true },
  { id: "processingTurnaround", label: "Processing turnaround", available: true },
  { id: "outputYield", label: "Output yield", available: true },
  { id: "serviceCompletionRate", label: "Service completion rate", available: true },
  { id: "serviceBacklog", label: "Service backlog", available: true },
  { id: "averageServiceLatency", label: "Average service latency", available: true },
  { id: "serviceErrorRate", label: "Service error rate", available: true },
  { id: "serviceErrorVolume", label: "Service error volume", available: true },
  { id: "stuckServiceJobs24h", label: "Stuck jobs over 24h", available: true },
  { id: "publishScheduleCompletionRate", label: "Publish schedule completion rate", available: true },
  { id: "publishThroughput", label: "Publish throughput", available: true },
  { id: "publishPlatformHealth", label: "Publish platform health", available: true },
  { id: "metadataCompleteness", label: "Metadata completeness", available: true },
  { id: "recordedQualityIssues", label: "Recorded quality issues", available: true },
  { id: "clipcutCompletionRate", label: "Clip-cut completion rate", available: true },
  { id: "downloads", label: "Downloads", available: false },
  { id: "views", label: "Views", available: false },
  { id: "revenue", label: "Revenue", available: false },
  { id: "creditConsumption", label: "Credit consumption", available: false }
] as const;

export const semanticDimensions = [
  "date",
  "company",
  "channel",
  "user",
  "language",
  "videoType",
  "serviceType",
  "sourcePlatform",
  "publishPlatform",
  "status"
] as const;
